### ISSUE TITLE
Request to add word and character count

### ISSUE THREAD

**Issue by azizly** [amitmerchant1990/notepad#17]
Hello, i work in a social media agency, and content writing, i make alot of use of a notepad that is usable on my browser, i wish https://notepad.js.org can have a word and character counter, so it  helps me when writing content for limited text boxes like twitter, or when i have a certain amount of words i want to reach.
Thanks

**Comment by amitmerchant1990** [comment]
Please don't create issues for new feature requests. Use "Discussions" for this kind of stuff.

**Comment by azizly** [comment]
Hello Ami, thank you very much, i am sorry to do it the wrong way, i am very ignorant when it comes to how GitHub is working. will make sure to follow the right procedures in future. 
    On Tuesday, 2 August 2022 at 08:56:03 GMT+4, Amit Merchant ***@***.***> wrote:  
 
 


Please don't create issues for new feature requests. Use "Discussions" for this kind of stuff.

**Comment by amitmerchant1990** [comment]
Implemented this feature in https://github.com/amitmerchant1990/notepad/pull/20
