### ISSUE TITLE
command-S not supported

### ISSUE THREAD

**Issue by benatkin** [amitmerchant1990/notepad#30]
The intro says to save with Crtl-S and Command-S but I'm on a Mac and Command-S didn't save. Appears to be missing from the code:

https://github.com/amitmerchant1990/notepad/blob/master/js/app.js#L231

**Comment by amitmerchant1990** [comment]
I'll take a look. 👍

**Comment by amitmerchant1990** [comment]
Fixed the issue with this commit: https://github.com/amitmerchant1990/notepad/commit/9c898c0e3af747bc94799f1ab28aa4cb76921fb5

**Comment by benatkin** [comment]
Nice! Thanks.
