### ISSUE TITLE
UI/UX Improvement

### ISSUE THREAD

**Issue by Binary-Vibes72** [amitmerchant1990/notepad#38]
Hiii sir/mam, 
I want to contribute to this project. I feel like making some UI/UX Improvement may lead to better user experience. 
I know few technologies which will helpful for this project. I am accepting from you to assign this issue to me and I am completely new to open source Contribution so its my first time.

Thank you.

**Comment by amitmerchant1990** [comment]
Can you suggest what you want to improve in terms of UI/UX here?

Give 2-3 bullet points if possible.

**Comment by Binary-Vibes72** [comment]
- Better Color Schemes
- Better Navigation for tools
- A better logo for making it more memorable to user
- Trending UI components to make it more elegant.
