### ISSUE TITLE
Emoji short codes in markdown are stretched

### ISSUE THREAD

**Issue by Person-Who-Exists** [amitmerchant1990/notepad#43]
When using short codes ex: `:smile:` the rendered emoji becomes extremely stretched and distorted:
![image](https://github.com/user-attachments/assets/c308ba65-9e82-485c-b62b-f2922007479f)

**Comment by amitmerchant1990** [comment]
I'll take a look.

Thanks for the heads up!

**Comment by Person-Who-Exists** [comment]
Resolved with pr #44
