### ISSUE TITLE
the dark/light theme toggle is not working as expected

### ISSUE THREAD

**Issue by iamheavymetalx7** [amitmerchant1990/notepad#47]
the dark to light theme version works fine, but once user gets into light theme mode, the user is unable to move to dark mode. even after multiple clicks it is not working.

I am open to working and fixing this bug.

**Comment by iamheavymetalx7** [comment]
@amitmerchant1990

**Comment by iamheavymetalx7** [comment]
Note: I tried this on firefox, the bug is not present there. but on chrome it is present

**Comment by amitmerchant1990** [comment]
I don't think so. I've tried this on multiple OS and browsers and it seems like it's working flawlessly.

Also, this feature has been there for quite a while now but I haven't heard from anyone else.

But check the console and see if there's any error and if that is the case, send me a screenshot of it.

**Comment by iamheavymetalx7** [comment]
Hi amit, there no errors on the console. I will share a video of the same: [Link](https://drive.google.com/file/d/1XI_V936IgUh_-9tCnKq46_hfkiWxkFQo/view?usp=sharing)

Current OS: macOS 15.1 (24B83)
Chrome Version: Version 131.0.6778.69 (Official Build) (arm64)

**Comment by amitmerchant1990** [comment]
I just tried it with Chrome on macOS. No issues whatsoever.

https://github.com/user-attachments/assets/90322e46-11ab-432f-b870-75b367d6200d

**Comment by iamheavymetalx7** [comment]
Yeah, i checked it for me as well. in incognito browser it is working fine but for my default chrome profile, it is not working. Seems more like a bug.
