### ISSUE TITLE
Red button isn't the destructive action in delete dialog

### ISSUE THREAD

**Issue by 1j01** [amitmerchant1990/notepad#5]
![image](https://user-images.githubusercontent.com/3630663/79705455-c5dad100-8283-11ea-8ac6-831536c4fb43.png)

Red buttons are normally reserved for destructive actions. That makes this confusing, and potentially someone could lose data because of this. Imagine someone *accidentally* clicks the trash button, reads the question, says no no no, and quickly clicks the not-red button.

Also, the "Yes, delete it!" doesn't match the question, which asks about a plural noun, and the "Yes" and "it" just add noise that make it less scan-able, i.e. less likely someone's going to actually read the button. So I would recommend saying just "Delete"

**Comment by amitmerchant1990** [comment]
Hey @1j01 I totally agree on these. I'll fix these issues based on your suggestions.

Thanks!

**Comment by amitmerchant1990** [comment]
Fix the concerned issue here 2b20be28ca8602ddb368977cc1b62ba090f447ac.
