### ISSUE TITLE
PWA Icon on iOS Missing

### ISSUE THREAD

**Issue by evg1n** [amitmerchant1990/notepad#6]
Congrats on this great app!

I added it on my homescreen using Safari iOS on my iPhone, it shows the webpage screenshot as an app icon.

You should have an "apple-touch-icon.png" (196x196px or 180x180px) in order to get it working properly.

Cheers.

**Comment by amitmerchant1990** [comment]
Added with this commit: https://github.com/amitmerchant1990/notepad/commit/c8231c83d989450cc2adc6edf493cc396092ebde
